<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="unittest/loader.py" name="unittest.loader._FailedTest-20191013150356" skipped="0" tests="1" time="0.004" timestamp="2019-10-13T15:03:56">
	<testcase classname="unittest.loader._FailedTest" file="/usr/lib/python3.6/unittest/loader.py" line="33" name="validate_colors_list_tests" time="0.004" timestamp="2019-10-13T15:03:56">
		<error message="Failed to import test module: validate_colors_list_tests
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/unittest/loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/student/Desktop/SystemProgramming/Projects/NolanWilliamsProject2/src/unittest/python/validate_colors_list_tests.py&quot;, line 3, in &lt;module&gt;
    from main.python.resistor import validateColorsList
ModuleNotFoundError: No module named 'main'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: validate_colors_list_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/student/Desktop/SystemProgramming/Projects/NolanWilliamsProject2/src/unittest/python/validate_colors_list_tests.py", line 3, in <module>
    from main.python.resistor import validateColorsList
ModuleNotFoundError: No module named 'main'

]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
