<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="validate_colors_list_tests.py" name="validate_colors_list_tests.TestValidateColorsList-20191013144703" skipped="0" tests="3" time="0.007" timestamp="2019-10-13T14:47:03">
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" file="src/unittest/python/validate_colors_list_tests.py" line="9" name="test4ColorsBands" time="0.000" timestamp="2019-10-13T14:47:03">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" file="src/unittest/python/validate_colors_list_tests.py" line="13" name="test5ColorBands" time="0.000" timestamp="2019-10-13T14:47:03">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" file="src/unittest/python/validate_colors_list_tests.py" line="19" name="test3ColorBands" time="0.006" timestamp="2019-10-13T14:47:03">
		<error message="'_AssertRaisesContext' object has no attribute 'getMessage'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/student/Desktop/SystemProgramming/Projects/NolanWilliamsProject2/src/unittest/python/validate_colors_list_tests.py", line 23, in test3ColorBands
    self.assertEqual(error.getMessage(), "There should only be 4 or 5 bands")
AttributeError: '_AssertRaisesContext' object has no attribute 'getMessage'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
